/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_attributes_SpeechPart */

#ifndef _Included_ru_lspl_text_attributes_SpeechPart
#define _Included_ru_lspl_text_attributes_SpeechPart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_attributes_SpeechPart
 * Method:    getAbbrevation
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_SpeechPart_getAbbrevation
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_lspl_text_attributes_SpeechPart
 * Method:    getTitle
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_SpeechPart_getTitle
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_lspl_text_attributes_SpeechPart
 * Method:    getPluralTitle
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_SpeechPart_getPluralTitle
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
