/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_patterns_Alternative_DependencyList */

#ifndef _Included_ru_lspl_patterns_Alternative_DependencyList
#define _Included_ru_lspl_patterns_Alternative_DependencyList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
