/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_Namespace */

#ifndef _Included_ru_lspl_Namespace
#define _Included_ru_lspl_Namespace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_Namespace
 * Method:    create
 * Signature: ([Lru/lspl/Namespace;)Lru/lspl/Namespace;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_Namespace_create
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ru_lspl_Namespace
 * Method:    getDefinedPatternCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_Namespace_getDefinedPatternCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_Namespace
 * Method:    getDefinedPattern
 * Signature: (I)Lru/lspl/patterns/Pattern;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_Namespace_getDefinedPattern__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_Namespace
 * Method:    getDefinedPattern
 * Signature: (Ljava/lang/String;)Lru/lspl/patterns/Pattern;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_Namespace_getDefinedPattern__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_lspl_Namespace
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_Namespace_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
