/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Loop */

#ifndef _Included_ru_lspl_text_Loop
#define _Included_ru_lspl_text_Loop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_Loop
 * Method:    getIterationCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_Loop_getIterationCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Loop
 * Method:    getIteration
 * Signature: (I)Lru/lspl/text/LoopIteration;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Loop_getIteration
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
