/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_attributes_AttributeKey */

#ifndef _Included_ru_lspl_text_attributes_AttributeKey
#define _Included_ru_lspl_text_attributes_AttributeKey
#ifdef __cplusplus
extern "C" {
#endif
#undef ru_lspl_text_attributes_AttributeKey_COUNT
#define ru_lspl_text_attributes_AttributeKey_COUNT 14L
/*
 * Class:     ru_lspl_text_attributes_AttributeKey
 * Method:    getAbbrevation
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_AttributeKey_getAbbrevation
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_lspl_text_attributes_AttributeKey
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_AttributeKey_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_lspl_text_attributes_AttributeKey
 * Method:    getTitle
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_AttributeKey_getTitle
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
