/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_MatchVariant */

#ifndef _Included_ru_lspl_text_MatchVariant
#define _Included_ru_lspl_text_MatchVariant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_MatchVariant
 * Method:    getTransitionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_MatchVariant_getTransitionCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_MatchVariant
 * Method:    getTransition
 * Signature: (I)Lru/lspl/text/Transition;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_MatchVariant_getTransition
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_text_MatchVariant
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_text_MatchVariant_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
