/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Text */

#ifndef _Included_ru_lspl_text_Text
#define _Included_ru_lspl_text_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_Text
 * Method:    create
 * Signature: (Ljava/lang/String;)Lru/lspl/text/Text;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Text_create__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ru_lspl_text_Text
 * Method:    create
 * Signature: (Ljava/lang/String;Lru/lspl/text/TextConfig;)Lru/lspl/text/Text;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Text_create__Ljava_lang_String_2Lru_lspl_text_TextConfig_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     ru_lspl_text_Text
 * Method:    getWordCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_Text_getWordCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_text_Text
 * Method:    getWord
 * Signature: (II)Lru/lspl/text/Word;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Text_getWord
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_lspl_text_Text
 * Method:    getMatchCount
 * Signature: (Lru/lspl/patterns/Pattern;)I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_Text_getMatchCount
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ru_lspl_text_Text
 * Method:    getMatch
 * Signature: (Lru/lspl/patterns/Pattern;I)Lru/lspl/text/Match;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Text_getMatch
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     ru_lspl_text_Text
 * Method:    dump
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_Text_dump
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Text
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_text_Text_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
