/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Text_MatchList */

#ifndef _Included_ru_lspl_text_Text_MatchList
#define _Included_ru_lspl_text_Text_MatchList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
