/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Loop */

#ifndef _Included_ru_lspl_text_Loop
#define _Included_ru_lspl_text_Loop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_Loop
 * Method:    getTransitionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_Loop_getTransitionCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Loop
 * Method:    getTransition
 * Signature: (I)Lru/lspl/text/Transition;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Loop_getTransition
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
