/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_attributes_IndexedAttribute */

#ifndef _Included_ru_lspl_text_attributes_IndexedAttribute
#define _Included_ru_lspl_text_attributes_IndexedAttribute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_attributes_IndexedAttribute
 * Method:    getAbbrevation
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_IndexedAttribute_getAbbrevation
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_lspl_text_attributes_IndexedAttribute
 * Method:    getTitle
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_attributes_IndexedAttribute_getTitle
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
