/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Text_NodeList */

#ifndef _Included_ru_lspl_text_Text_NodeList
#define _Included_ru_lspl_text_Text_NodeList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
