/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Transition */

#ifndef _Included_ru_lspl_text_Transition
#define _Included_ru_lspl_text_Transition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_Transition
 * Method:    getFragment
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_Transition_getFragment
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Transition
 * Method:    dump
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_Transition_dump
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Transition
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_text_Transition_finalize
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Transition
 * Method:    getAttribute
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Transition_getAttribute
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
