/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Match */

#ifndef _Included_ru_lspl_text_Match
#define _Included_ru_lspl_text_Match
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_Match
 * Method:    getVariantCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_Match_getVariantCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Match
 * Method:    getVariant
 * Signature: (I)Lru/lspl/text/MatchVariant;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Match_getVariant
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
