/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_patterns_PatternBuilder */

#ifndef _Included_ru_lspl_patterns_PatternBuilder
#define _Included_ru_lspl_patterns_PatternBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_patterns_PatternBuilder
 * Method:    create
 * Signature: ()Lru/lspl/patterns/PatternBuilder;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_patterns_PatternBuilder_create
  (JNIEnv *, jclass);

/*
 * Class:     ru_lspl_patterns_PatternBuilder
 * Method:    getDefinedPatternCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_patterns_PatternBuilder_getDefinedPatternCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_patterns_PatternBuilder
 * Method:    getDefinedPattern
 * Signature: (I)Lru/lspl/patterns/Pattern;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_patterns_PatternBuilder_getDefinedPattern__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_patterns_PatternBuilder
 * Method:    getDefinedPattern
 * Signature: (Ljava/lang/String;)Lru/lspl/patterns/Pattern;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_patterns_PatternBuilder_getDefinedPattern__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_lspl_patterns_PatternBuilder
 * Method:    build
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_lspl_patterns_PatternBuilder_build
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_lspl_patterns_PatternBuilder
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_patterns_PatternBuilder_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
