/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Node_TransitionList */

#ifndef _Included_ru_lspl_text_Node_TransitionList
#define _Included_ru_lspl_text_Node_TransitionList
#ifdef __cplusplus
extern "C" {
#endif
#undef ru_lspl_text_Node_TransitionList_MAX_ARRAY_SIZE
#define ru_lspl_text_Node_TransitionList_MAX_ARRAY_SIZE 2147483639L
#ifdef __cplusplus
}
#endif
#endif
