/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_LsplObject */

#ifndef _Included_ru_lspl_LsplObject
#define _Included_ru_lspl_LsplObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_LsplObject
 * Method:    dumpMemoryStats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_LsplObject_dumpMemoryStats
  (JNIEnv *, jclass);

/*
 * Class:     ru_lspl_LsplObject
 * Method:    setRml
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_lspl_LsplObject_setRml
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ru_lspl_LsplObject
 * Method:    initStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_LsplObject_initStatic
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
