/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Node */

#ifndef _Included_ru_lspl_text_Node
#define _Included_ru_lspl_text_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_Node
 * Method:    getTransition
 * Signature: (I)Lru/lspl/text/Transition;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_Node_getTransition
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_text_Node
 * Method:    getTransitionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_Node_getTransitionCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Node
 * Method:    dump
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_text_Node_dump
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_Node
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_text_Node_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
