/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_MatchVariant_TransitionList */

#ifndef _Included_ru_lspl_text_MatchVariant_TransitionList
#define _Included_ru_lspl_text_MatchVariant_TransitionList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
