/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Loop_IterationList */

#ifndef _Included_ru_lspl_text_Loop_IterationList
#define _Included_ru_lspl_text_Loop_IterationList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
