/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_Match_VariantList */

#ifndef _Included_ru_lspl_text_Match_VariantList
#define _Included_ru_lspl_text_Match_VariantList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
