/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_patterns_Alternative */

#ifndef _Included_ru_lspl_patterns_Alternative
#define _Included_ru_lspl_patterns_Alternative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_patterns_Alternative
 * Method:    getMatcherCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_patterns_Alternative_getMatcherCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_patterns_Alternative
 * Method:    getSource
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_patterns_Alternative_getSource
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_patterns_Alternative
 * Method:    dump
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_lspl_patterns_Alternative_dump
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_patterns_Alternative
 * Method:    getDependencyCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_patterns_Alternative_getDependencyCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_patterns_Alternative
 * Method:    getDependency
 * Signature: (I)Lru/lspl/patterns/Pattern;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_patterns_Alternative_getDependency
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_patterns_Alternative
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_lspl_patterns_Alternative_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
