/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_patterns_PatternBuilder_DefinedPatternList */

#ifndef _Included_ru_lspl_patterns_PatternBuilder_DefinedPatternList
#define _Included_ru_lspl_patterns_PatternBuilder_DefinedPatternList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
