/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_lspl_text_LoopIteration */

#ifndef _Included_ru_lspl_text_LoopIteration
#define _Included_ru_lspl_text_LoopIteration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_lspl_text_LoopIteration
 * Method:    getVariantCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_LoopIteration_getVariantCount
  (JNIEnv *, jobject);

/*
 * Class:     ru_lspl_text_LoopIteration
 * Method:    getVariant
 * Signature: (I)Lru/lspl/text/LoopIterationVariant;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_LoopIteration_getVariant
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_text_LoopIteration
 * Method:    getVariantTransitionCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_lspl_text_LoopIteration_getVariantTransitionCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_lspl_text_LoopIteration
 * Method:    getVariantTransition
 * Signature: (II)Lru/lspl/text/Transition;
 */
JNIEXPORT jobject JNICALL Java_ru_lspl_text_LoopIteration_getVariantTransition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_lspl_text_LoopIteration
 * Method:    finalizeVariant
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_lspl_text_LoopIteration_finalizeVariant
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
